function folder_(a){if(a.folderId)return DriveApp.getFolderById(a.folderId);
const p=get_('Pessoas',a.pessoaId);
const root=DriveApp.getFolderById(props_().getProperty('ROOT_FOLDER_ID'));
const name=(a.id+' — '+p.nome+' — '+a.demanda+' — '+a.referencia).slice(0,230);
const all=root.getFolders();
const matches=[];
while(all.hasNext()){const f=all.next();
if(f.getName().startsWith(a.id+' — '))matches.push(f);
}if(matches.length>1)fail_('Há pastas duplicadas para este atendimento; administração deve reconciliar.');
return matches.length?matches[0]:root.createFolder(name);
}
function upload_(ctx,q){const a=get_('Atendimentos',q.atendimentoId);
version_(a,q.versao);
const c=cfg_();
if(!c.categorias.includes(q.categoria))fail_('Categoria inválida.');
if(!['application/pdf','image/jpeg','image/png'].includes(q.mime))fail_('Use PDF, JPEG ou PNG.');
if(typeof q.base64!=='string'||q.base64.length>PDA.maxBytes*1.4)fail_('Limite de 5 MB por arquivo.');
const bytes=Utilities.base64Decode(q.base64);
if(!bytes.length||bytes.length>PDA.maxBytes)fail_('Arquivo vazio ou maior que 5 MB.');
const sig=bytes.slice(0,8).map(x=>(x+256)%256);
if((q.mime==='application/pdf'&&String.fromCharCode(...sig.slice(0,5))!=='%PDF-')||(q.mime==='image/jpeg'&&(sig[0]!==255||sig[1]!==216))||(q.mime==='image/png'&&sig.join(',')!=='137,80,78,71,13,10,26,10'))fail_('Conteúdo não corresponde ao tipo do arquivo.');
const digest=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes).map(x=>('0'+((x+256)%256).toString(16)).slice(-2)).join('');
const prior=all_('Documentos').find(d=>d.atendimentoId===a.id&&d.categoria===q.categoria&&d.hash===digest&&bool_(d.vigente));
if(prior)return {documento:prior,atendimento:a,mensagem:'Arquivo já anexado; preservado sem duplicação.'};
if(q.categoria==='RESIDENCIA')date_(q.vencimento);
let previous=null;
if(q.substituiId){previous=get_('Documentos',q.substituiId);
if(previous.atendimentoId!==a.id||previous.categoria!==q.categoria||!bool_(previous.vigente))fail_('Substituição inválida.');
}const folder=folder_(a);
const did=id_('DOC',ctx.op);
const ext={'application/pdf':'pdf','image/jpeg':'jpg','image/png':'png'}[q.mime];
const name=a.id+'_'+q.categoria+'_'+did+'.'+ext;
const it=folder.getFilesByName(name);
const f=it.hasNext()?it.next():folder.createFile(Utilities.newBlob(bytes,q.mime,name));
if(it.hasNext())fail_('Arquivos duplicados exigem reconciliação.');
ctx.effects.push('Arquivo preservado no Drive: '+f.getUrl());
if(previous)change_(ctx,'Documentos',previous.id,Object.assign({},previous,{vigente:false}),previous.versao);
const d=change_(ctx,'Documentos',did,{atendimentoId:a.id,categoria:q.categoria,fileId:f.getId(),url:f.getUrl(),nome:name,hash:digest,mime:q.mime,substituiId:q.substituiId||'',vigente:true,vencimento:q.vencimento||'',terceiro:bool_(q.terceiro),conferido:false});
const changed=touch_(ctx,Object.assign({},a,{folderId:folder.getId()}));
return {documento:d,atendimento:changed,mensagem:'Arquivo gravado. Conferência humana pendente.'};
}
