const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const base=__dirname;
const read=name=>fs.readFileSync(path.join(base,name),'utf8');
const backend=read('CONSULTA_V2.gs');
for(const fn of ['personListLite_','personQuickSummary_','personFichaMeta_','personDocumentsPage_','personProcessesPage_','personAttendancesPage_','personHistoryPage_','taskCreateOptions_']) assert.ok(backend.includes('function '+fn+'('),fn);
const api=read('06_Modulos.gs');
for(const action of ['pessoasLeve','pessoaResumo','pessoaFichaMeta','pessoaDocumentos','pessoaProcessos','pessoaAtendimentos','pessoaHistorico','tarefaCriarOpcoes']) assert.ok(api.includes(action),action);
const app=read('App_Script.html');
for(const action of ['pessoasLeve','pessoaResumo','pessoaFichaMeta','pessoaDocumentos','pessoaProcessos','pessoaAtendimentos','pessoaHistorico','tarefaCriarOpcoes']) assert.ok(app.includes(action),action);
const acomp=read('ACOMP_Script.html');
for(const token of ['pessoasLeve','openPersonDrawer','prefetchPersonSummary','PDA_ACOMP_LIST_V2','+ Tarefa','Abrir ficha']) assert.ok(acomp.includes(token),token);
const app=read('App_Script.html');
for(const token of ['openPersonDrawer_','createTaskForPerson_','deletePersonFromUi_','pessoaFichaMeta','pessoaDocumentos','pessoaAtendimentos','pessoaProcessos','pessoaHistorico']) assert.ok(app.includes(token),token);
console.log('PASS etapas 1 e 2: consultas leves, drawer e ficha lazy conectadas.');
