// Verificação estrutural/interação em DOM simulado. Não substitui navegador real.
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');const src=path.join(__dirname,'../src');let context;
class Node{constructor(tag,text=''){this.tag=tag;this.children=[];this.textContent=text;this.dataset={};this.attributes={};this.value='';this.checked=false;}append(...xs){for(const x of xs){x.parent=this;this.children.push(x);if(this.tag==='head'&&x.tag==='script')vm.runInContext(x.textContent,context);}}replaceChildren(...xs){this.children=[];this.append(...xs)}setAttribute(k,v){this.attributes[k]=v}get firstChild(){return this.children[0]}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this)}insertBefore(x,b){x.parent=this;this.children.splice(Math.max(0,this.children.indexOf(b)),0,x)}set innerHTML(v){this.replaceChildren(new Node('section'))}get elements(){return {namedItem:n=>this.walk().find(x=>x.name===n)}}walk(){return [this,...this.children.flatMap(x=>x.walk?x.walk():[])]}querySelector(s){return this.walk().find(x=>x.tag===s)}reportValidity(){return true}}
const root=new Node('body'),head=new Node('head');const ids={};for(const id of ['nav','status','app','identity']){ids[id]=new Node('div');root.append(ids[id]);}const document={head,createElement:t=>new Node(t),getElementById:id=>ids[id],querySelectorAll:sel=>sel.includes('#nav')?ids.nav.walk().filter(x=>x.tag==='button'):root.walk().filter(x=>x.tag==='button')};
const config={municipios:['Rio Grande'],entidades:['COLÔNIA Z-1','Outro'],demandas:['Seguro-Defeso 2025'],categorias:['RG_CPF'],rascunhos:'PENDENTE'};const person={id:'P1',nome:'Pessoa Fictícia',cpf:'01234567890',uf:'RS',versao:1};const a={id:'A1',pessoaId:'P1',demanda:'Seguro-Defeso 2025',referencia:'Teste',situacao:'EM_PREPARACAO',versao:1};const modulos={PAINEL:'Painel',PESS:'Pessoas',ATEND:'Atendimentos',ACOMP:'Ficha',MIN:'Minutas',ADM:'Admin',DIST:'Distribuição',PROC:'Processos'};const store=new Map();
function backend(action,q){switch(action){case 'bootstrap':return {email:'admin@example.test',perfil:'ADMIN',config,modulos};case 'pessoas':return [person];case 'pessoa':return person;case 'painel':return {pessoas:1,atendimentos:1,pendencias:0,conferencias:1,minutas:0,registros:[a],pendenciasRegistros:[],minutasRegistros:[]};case 'ficha':return {pessoa:person,atendimentos:[a],documentos:[],minutas:[],pendencias:[],historico:[],processos:[],aptidao:[{id:'A1',pendencias:['Anexar RG/CPF']}]};case 'admin':return {configuracoes:[{chave:'rascunhos',valor:'"PENDENTE"',versao:1},{chave:'municipios',valor:'["Rio Grande"]',versao:1}],usuarios:[{email:'admin@example.test',perfil:'ADMIN',ativo:'true'}],perfis:['ADMIN','CONSULTA']};default:throw Error('API não simulada: '+action)}}
function runner(){let good,bad;const p=new Proxy({}, {get:(_,k)=>k==='withSuccessHandler'?fn=>{good=fn;return p}:k==='withFailureHandler'?fn=>{bad=fn;return p}:(...args)=>Promise.resolve().then(()=>{try{if(k==='api')good(backend(...args));else if(k==='carregarModulo'){const code=args[0];good({view:fs.readFileSync(path.join(src,code+'_View.html'),'utf8'),style:fs.readFileSync(path.join(src,code+'_Style.html'),'utf8'),script:fs.readFileSync(path.join(src,code+'_Script.html'),'utf8')});}else throw Error(k);}catch(e){bad(e);}})});return p;}
context={document,console,TextEncoder,crypto:crypto.webcrypto,sessionStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},Option:function(label,value){const n=new Node('option',label);n.value=value;return n},google:{script:{get run(){return runner()}}},window:{}};vm.createContext(context);const code=fs.readFileSync(path.join(src,'App_Script.html'),'utf8').replace(/^\s*<script>/,'').replace(/<\/script>\s*$/,'').replace(/\}\)\(\);\s*App\.start\(\);/,'})();');vm.runInContext(code,context);
(async()=>{await vm.runInContext('App.start()',context);for(const key of Object.keys(modulos)){await vm.runInContext('App.go('+JSON.stringify(key)+',"P1")',context);if(ids.status.className?.includes('error'))throw Error(ids.status.textContent);assert(ids.app.walk().some(x=>x.tag==='h2'));console.log('PASS carregamento '+key);}await vm.runInContext('App.go("PESS")',context);const form=ids.app.walk().find(x=>x.tag==='form');await form.onsubmit({preventDefault(){}});assert(ids.app.walk().some(x=>x.textContent==='Pessoa Fictícia'));console.log('PASS busca de pessoa e renderização dos resultados');assert(!ids.app.walk().some(x=>x.tag==='script'));console.log('9 verificações de interface em DOM simulado aprovadas.');})().catch(e=>{console.error(e);process.exitCode=1});
