const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const path=require('path');const src=path.join(__dirname,'../src');
let email='admin@example.test',failBatch=false,loseReply=false;const properties={OWNER_EMAIL:email};let counter=0;const files=new Map(),folders=new Map(),books=new Map();
const iter=items=>{let i=0;return {hasNext:()=>i<items.length,next:()=>items[i++]};};
class File{constructor(name,mime,bytes=[]){this.id='file-'+(++counter);this.name=name;this.mime=mime;this.bytes=bytes;this.modified=1;files.set(this.id,this);}getId(){return this.id}getName(){return this.name}getMimeType(){return this.mime}isTrashed(){return false}getUrl(){return 'https://drive.google.com/file/d/'+this.id}moveTo(f){this.folder=f.id;return this}getLastUpdated(){return new Date(this.modified)}makeCopy(name,f){const copy=new File(name,this.mime);copy.text=this.text;copy.folder=f.id;return copy;}}
class Folder{constructor(name){this.id='folder-'+(++counter);this.name=name;folders.set(this.id,this);}getId(){return this.id}getName(){return this.name}getUrl(){return 'https://drive.google.com/drive/folders/'+this.id}createFolder(name){const f=new Folder(name);f.parent=this.id;return f}getFolders(){return iter([...folders.values()].filter(f=>f.parent===this.id))}getFoldersByName(name){return iter([...folders.values()].filter(f=>f.parent===this.id&&f.name===name))}getFilesByName(name){return iter([...files.values()].filter(f=>f.folder===this.id&&f.name===name))}createFile(blob){const f=new File(blob.name,blob.mime,blob.bytes);f.folder=this.id;return f}}
class Sheet{constructor(name){this.name=name;this.id=++counter;this.rows=[];this.max=1000;}getSheetId(){return this.id}getLastRow(){return this.rows.length}getLastColumn(){return Math.max(0,...this.rows.map(r=>r.length))}getMaxRows(){return this.max}setFrozenRows(){}getDataRange(){return this.getRange(1,1,Math.max(1,this.getLastRow()),Math.max(1,this.getLastColumn()))}getRange(row,col,n=1,m=1){const sh=this;const r={getDisplayValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>String(sh.rows[row-1+i]?.[col-1+j]??''))),setValues:values=>{values.forEach((v,i)=>{sh.rows[row-1+i]??=[];v.forEach((x,j)=>sh.rows[row-1+i][col-1+j]=x)});return r;},setBackground:()=>r,setFontColor:()=>r,setNumberFormat:()=>r};return r;}}
class Book{constructor(name){const f=new File(name,'sheets');this.id=f.id;this.sheets=[];books.set(this.id,this);}getId(){return this.id}getUrl(){return 'https://docs.google.com/spreadsheets/d/'+this.id}setSpreadsheetTimeZone(){}getSheetByName(n){return this.sheets.find(s=>s.name===n)}insertSheet(n){const s=new Sheet(n);this.sheets.push(s);return s}}
const parent=new Folder('authorized parent');folders.set('1wKO6B73R2e-H8E5R_vxRAHmUOIFz3bu7',parent);
const context={console,Date,JSON,Math,Object,Array,String,Number,Boolean,RegExp,Error,Set,Buffer,
 PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k],setProperty:(k,v)=>properties[k]=v})},Session:{getActiveUser:()=>({getEmail:()=>email})},ScriptApp:{getScriptId:()=> 'independent-project'},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},MimeType:{GOOGLE_SHEETS:'sheets',GOOGLE_DOCS:'docs'},
 Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,x)=>[...crypto.createHash('sha256').update(typeof x==='string'?x:Buffer.from(x)).digest()],base64Decode:x=>[...Buffer.from(x,'base64')],newBlob:(bytes,mime,name)=>({bytes,mime,name}),formatDate:()=> '05/10/2026'},
 DriveApp:{getFolderById:id=>folders.get(id)||assert.fail('missing folder'),getFileById:id=>files.get(id)||assert.fail('missing file '+id),getFilesByName:name=>iter([...files.values()].filter(f=>f.name===name))},
 SpreadsheetApp:{openById:id=>books.get(id),create:name=>new Book(name),flush:()=>{}},
 Sheets:{Spreadsheets:{batchUpdate:({requests},id)=>{if(failBatch){failBatch=false;throw Error('Falha Sheets simulada');}const book=books.get(id);for(const req of requests){if(req.appendDimension){book.sheets.find(s=>s.id===req.appendDimension.sheetId).max+=req.appendDimension.length;continue;}const u=req.updateCells;const s=book.sheets.find(s=>s.id===u.range.sheetId);s.rows[u.range.startRowIndex]=u.rows[0].values.map(v=>v.userEnteredValue.stringValue);}if(loseReply){loseReply=false;throw Error('Resposta perdida após confirmação');}}}},
 DocumentApp:{TabType:{DOCUMENT_TAB:'doc'},openById:id=>{const f=files.get(id);const body={getText:()=>f.text,findText:token=>{const start=f.text.indexOf(token);return start<0?null:{getStartOffset:()=>start,getEndOffsetInclusive:()=>start+token.length-1,getElement:()=>({asText:()=>({getAttributes:()=>({}),deleteText:(a,b)=>f.text=f.text.slice(0,a)+f.text.slice(b+1),insertText:(a,t)=>f.text=f.text.slice(0,a)+t+f.text.slice(a),setAttributes:()=>{}})})}}};return {getTabs:()=>[{getType:()=> 'doc',asDocumentTab:()=>({getBody:()=>body,getHeader:()=>null,getFooter:()=>null}),getChildTabs:()=>[]}],saveAndClose:()=>{}};}}
};vm.createContext(context);vm.runInContext(fs.readdirSync(src).filter(f=>f.endsWith('.gs')).sort().map(f=>fs.readFileSync(path.join(src,f),'utf8')).join('\n'),context);
const C=context;const run=(a,p={})=>C.api(a,{...p,op:p.op||crypto.randomUUID()});let passed=0;function test(name,fn){fn();console.log('PASS '+name);passed++;}const rows=t=>C.all_(t);const fresh=(t,id)=>C.get_(t,id);const config=(key,val)=>{const r=rows('Configuracoes').find(r=>r.chave===key);run('configSalvar',{chave:key,valor:val,versao:r.versao})};
let p,a,d;
test('instalação repetida preserva IDs, recursos e configurações',()=>{C.instalar();const ids=JSON.stringify(properties),n=files.size,f=folders.size;C.instalar();assert.equal(JSON.stringify(properties),ids);assert.equal(files.size,n);assert.equal(folders.size,f);assert.equal(rows('Usuarios').length,1);});
test('CPF com zero inicial, telefone celular, data válida',()=>{p=run('pessoaSalvar',{nome:'Pessoa Fictícia Teste',cpf:'01234567890',nascimento:'29/02/2000',telefone:'(53) 99632-1234',tipoVia:'Rua',via:'Via Fictícia',numero:'105',complemento:'Ap 101',bairro:'Centro',cidade:'Rio Grande',uf:'RS',entidade:'COLÔNIA Z-1',analfabeto:'NAO'});assert.equal(p.cpf,'01234567890');});
test('bloqueio de CPF inválido, data impossível e nascimento futuro',()=>{assert.throws(()=>C.cpf_('11111111111'));assert.throws(()=>C.date_('31/02/2025'));assert.throws(()=>C.validatePerson_({...p,nascimento:'06/10/2026'},C.cfg_(),true));});
test('duplicação de pessoa bloqueada',()=>assert.throws(()=>run('pessoaSalvar',{...p,id:'',versao:undefined}),/CPF já/));
test('rascunho não libera campos sem decisão expressa',()=>assert.throws(()=>run('pessoaSalvar',{nome:'Incompleto',cpf:'52998224725'}),/Informe/));
test('criação de atendimento e reenvio idempotente',()=>{const q={pessoaId:p.id,demanda:'Seguro-Defeso 2025',referencia:'TESTE 2025',parcelas:'Somente a última de 2025',enderecamento:'AO JUÍZO TESTE',secaoJudiciaria:'SEÇÃO TESTE',valorCausa:'6.518,00',localData:'Rio Grande, data da distribuição',op:crypto.randomUUID()};a=run('atendimentoSalvar',q);assert.equal(run('atendimentoSalvar',q).id,a.id);assert.equal(rows('Atendimentos').length,1);assert.throws(()=>run('atendimentoSalvar',{...q,referencia:'OUTRA'}),/conteúdo diferente/);});
test('duplicação da demanda bloqueada; outra referência permitida',()=>{assert.throws(()=>run('atendimentoSalvar',{...a,id:''}),/já cadastradas/);const b=run('atendimentoSalvar',{...a,id:'',referencia:'OUTRA DEMANDA',parcelas:'Outros casos',outrosCasos:'Demanda distinta para teste'});assert.notEqual(a.id,b.id);});
test('concorrência rejeita segunda atualização e registra antes/depois',()=>{const original=p;p=run('pessoaSalvar',{...p,numero:'106'});assert.throws(()=>run('pessoaSalvar',{...original,numero:'107'}),/CONFLITO/);const h=rows('Historico').filter(h=>h.registroId===p.id).at(-1);assert.equal(JSON.parse(h.antes).numero,'105');assert.equal(JSON.parse(h.depois).numero,'106');a=fresh('Atendimentos',a.id);});
test('encaminhamento incompleto bloqueado',()=>assert.throws(()=>run('encaminhar',{id:a.id,versao:a.versao}),/Definir política/));
test('falha Sheets depois do Drive e reenvio sem duplicar arquivo/pasta',()=>{config('vencimentoFuturo','RECUSAR');config('anexoOrientacao','Anexo fictício apenas para testes');const q={atendimentoId:a.id,versao:a.versao,categoria:'RG_CPF',mime:'application/pdf',base64:Buffer.from('%PDF-1.4 TESTE').toString('base64'),op:crypto.randomUUID()};failBatch=true;assert.throws(()=>run('upload',q),/Arquivo preservado/);const n=files.size,f=folders.size;const out=run('upload',q);d=out.documento;a=out.atendimento;assert.equal(files.size,n);assert.equal(folders.size,f);assert.equal(rows('Documentos').length,1);});
test('resposta perdida após commit retorna mesmo resultado no reenvio',()=>{const q={...p,via:'Via Alterada',op:crypto.randomUUID()};loseReply=true;assert.throws(()=>run('pessoaSalvar',q),/Resposta perdida/);p=run('pessoaSalvar',q);assert.equal(p.versao,3);a=fresh('Atendimentos',a.id);});
test('substituição mantém versão anterior e invalida conferência',()=>{const out=run('upload',{atendimentoId:a.id,versao:a.versao,categoria:'RG_CPF',mime:'application/pdf',base64:Buffer.from('%PDF-1.4 NOVA VERSAO').toString('base64'),substituiId:d.id});assert.equal(fresh('Documentos',d.id).vigente,'false');a=out.atendimento;d=out.documento;assert.equal(rows('Documentos').length,2);});
test('assinatura incompatível com MIME é rejeitada',()=>assert.throws(()=>run('upload',{atendimentoId:a.id,versao:a.versao,categoria:'PESCA',mime:'application/pdf',base64:Buffer.from('<script>bad</script>').toString('base64')}),/Conteúdo/));
test('todas categorias anexadas não equivalem à conferência',()=>{for(const categoria of C.cfg_().categorias.filter(c=>c!=='RG_CPF')){const out=run('upload',{atendimentoId:a.id,versao:a.versao,categoria,mime:'application/pdf',base64:Buffer.from('%PDF-1.4 '+categoria).toString('base64'),vencimento:categoria==='RESIDENCIA'?'06/08/2026':'',terceiro:categoria==='RESIDENCIA'});a=out.atendimento;}assert.equal(C.eligibility_(a,false).length,0);assert.ok(C.eligibility_(a,true).length>0);});
test('limite inclusivo de 60 dias, 61 dias e futuro',()=>{const doc=rows('Documentos').find(d=>d.categoria==='RESIDENCIA');const sheet=C.ss_().getSheetByName('Documentos'),heads=C.headers_('Documentos'),idx=C.row_('Documentos',doc.id);sheet.rows[idx][heads.indexOf('vencimento')]='05/08/2026';C.resetData_();assert.ok(C.eligibility_(a,false).some(x=>x.includes('60 dias')));sheet.rows[idx][heads.indexOf('vencimento')]='06/10/2026';C.resetData_();assert.ok(C.eligibility_(a,false).some(x=>x.includes('futuro')));config('vencimentoFuturo','ACEITAR');assert.equal(C.eligibility_(a,false).length,0);sheet.rows[idx][heads.indexOf('vencimento')]='06/08/2026';C.resetData_();});
test('conferência completa, terceiro, processo e anexo',()=>{for(const doc of rows('Documentos').filter(d=>d.vigente==='true')){run('documentoConferir',{...doc,conferido:true,declaracaoTerceiro:true,processoCompleto:true,anexoPresente:true,atendimentoVersao:a.versao});a=fresh('Atendimentos',a.id);}a=run('encaminhar',{id:a.id,versao:a.versao});a=run('atendimentoConferir',{id:a.id,versao:a.versao});assert.equal(a.situacao,'CONFERIDO');});
test('geração do modelo certo, bloqueio de desconhecidos e preservação original',()=>{const template=new File('modelo','docs');template.text=vm.runInContext('PLACEHOLDERS',context).map(k=>'<<'+k+'>>').join('\n');config('templateId',template.id);config('templateAprovado',true);const m=run('minutaGerar',{id:a.id,versao:a.versao});assert.ok(files.get(m.fileId).text.includes('Pessoa Fictícia'));assert.ok(!files.get(m.fileId).text.includes('<<'));assert.ok(template.text.includes('<<'));const bad=new File('ruim','docs');bad.text=template.text+'<<DESCONHECIDO>>';assert.throws(()=>C.validateTemplate_(bad.id),/desconhecidos/);});
test('edição posterior sinaliza minuta desatualizada e bloqueia revisão',()=>{p=run('pessoaSalvar',{...p,numero:'999'});a=fresh('Atendimentos',a.id);const m=C.dossier_({pessoaId:p.id}).minutas[0];assert.equal(m.desatualizada,true);assert.throws(()=>run('minutaRevisar',{id:m.id,versao:m.versao}),/alterados/);});
test('modelo da última parcela bloqueado para outros casos',()=>{const b=rows('Atendimentos').find(x=>x.id!==a.id);assert.throws(()=>run('minutaGerar',{id:b.id,versao:b.versao}),/modelo aprovado/);});
test('permissões são verificadas no servidor e identidade vazia bloqueia',()=>{email='intruso@example.test';assert.throws(()=>run('pessoas'),/não autorizado/);email='';assert.throws(()=>run('painel'),/Identidade/);email='admin@example.test';const u=run('usuarioSalvar',{email:'consulta@example.test',perfil:'CONSULTA',ativo:true});email=u.email;assert.ok(run('pessoas').length);assert.throws(()=>run('pessoaSalvar',{...p,numero:'1'}),/não autorizado/);email='admin@example.test';});
test('texto de fórmula gravado como string, nunca fórmula Sheets',()=>{p=run('pessoaSalvar',{...p,complemento:'=IMPORTXML("example", "x")'});assert.equal(fresh('Pessoas',p.id).complemento,'=IMPORTXML("example", "x")');});
test('pendência aberta bloqueia fluxo; resolução preserva histórico',()=>{a=fresh('Atendimentos',a.id);let pen=run('pendenciaSalvar',{atendimentoId:a.id,atendimentoVersao:a.versao,descricao:'Conferir dado fictício',situacao:'ABERTA'});a=fresh('Atendimentos',a.id);assert.ok(C.eligibility_(a,true).some(x=>x.includes('pendências abertas')));run('pendenciaSalvar',{...pen,atendimentoVersao:a.versao,situacao:'RESOLVIDA'});a=fresh('Atendimentos',a.id);assert.ok(!C.eligibility_(a,true).some(x=>x.includes('pendências abertas')));});
test('analfabetismo exige conferência a rogo e duas testemunhas',()=>{p=run('pessoaSalvar',{...p,analfabeto:'SIM'});a=fresh('Atendimentos',a.id);assert.ok(C.eligibility_(a,true).some(x=>x.includes('rogo')));const doc=rows('Documentos').find(x=>x.categoria==='PROCURACAO');run('documentoConferir',{...doc,atendimentoVersao:a.versao,rogo:true,testemunhas:true,conferido:true});a=fresh('Atendimentos',a.id);assert.ok(!C.eligibility_(a,true).some(x=>x.includes('rogo')));});
test('campos obrigatórios e placeholders inseridos nos dados bloqueiam minuta',()=>{assert.throws(()=>C.values_({...a,valorCausa:''},p),/VALOR_CAUSA/);assert.throws(()=>C.values_(a,{...p,nome:'<<INDEVIDO>>'}),/marcador/);});
test('reenvio do mesmo conteúdo em outra operação mantém único documento vigente',()=>{const before=rows('Documentos').length;const q={atendimentoId:a.id,versao:a.versao,categoria:'RG_CPF',mime:'application/pdf',base64:Buffer.from('%PDF-1.4 NOVA VERSAO').toString('base64')};const out=run('upload',q);assert.equal(rows('Documentos').length,before);assert.equal(out.documento.id,d.id);});
test('substituição cruzada entre atendimentos é bloqueada',()=>{const b=rows('Atendimentos').find(x=>x.id!==a.id);assert.throws(()=>run('upload',{atendimentoId:b.id,versao:b.versao,categoria:'RG_CPF',mime:'application/pdf',base64:Buffer.from('%PDF-1.4 CROSS').toString('base64'),substituiId:d.id}),/Substituição inválida/);});
test('instalação posterior preserva registros e decisões administrativas',()=>{const count=rows('Pessoas').length;C.instalar();assert.equal(rows('Pessoas').length,count);assert.equal(C.cfg_().vencimentoFuturo,'ACEITAR');});
console.log('\n'+passed+' cenários locais aprovados. Google Drive/Sheets/Docs são simulados; não constituem homologação Google.');
