const assert=require('node:assert/strict'),crypto=require('node:crypto');
const {C,vm}=require('./tests/apps-script-fixture.cjs');
let seq=0;
const op=()=>`TASK_TEST_${++seq}_${crypto.randomUUID()}`;
const context=(email)=>({email,op:op(),hash:'test-'+seq,changes:[],effects:[]});
const as=(email)=>vm.runInContext('PDA_AUTH_CONTEXT_EMAIL_='+JSON.stringify(email),C);
const commit=(ctx,result)=>C.commit_(ctx,result);
function addUser(email,nome,perfil='ALUNO',funcao='Aluno'){
 const ctx=context('admin@example.test');
 const id=C.id_('USR',email);
 const row=C.change_(ctx,'Usuarios',id,{email,perfil,ativo:true,nome,funcao});
 commit(ctx,row); return row;
}
C.instalar_();
addUser('responsavel@example.test','Responsável Teste');
addUser('segundo@example.test','Segundo Responsável');
const ss=C.ss_();
const expected=C.headers_('Tarefas');
const tarefas=ss.getSheetByName('Tarefas');
tarefas.rows[0]=expected.slice(0,expected.length-5);
ss.sheets=ss.sheets.filter(sh=>!['TarefaMensagens','TarefaAnexos','TarefaLeituras'].includes(sh.name));
C.resetData_();
as('admin@example.test');
const createCtx=context('admin@example.test');
const created=C.generalTaskCreate_(createCtx,{titulo:'Conferir documentos',descricao:'Conferir o documento anexado.',responsavel:'responsavel@example.test',prioridade:'ALTA',prazo:'2026-10-25'});
commit(createCtx,created);
assert.equal(C.get_('Tarefas',created.tarefa.id).titulo,'Conferir documentos');
assert.deepEqual(Array.from(C.ss_().getSheetByName('Tarefas').rows[0]),Array.from(expected));
for(const name of ['TarefaMensagens','TarefaAnexos','TarefaLeituras']) assert.ok(C.ss_().getSheetByName(name),name+' não criada');
console.log('PASS criação e migração aditiva das tarefas');
as('responsavel@example.test');
let notifications=C.taskNotifications_();
assert.equal(notifications.naoLidas,1);
assert.equal(notifications.itens[0].id,created.tarefa.id);
const seenCtx=context('responsavel@example.test');
const seen=C.taskNotificationsMarkSeen_(seenCtx); commit(seenCtx,seen);
assert.equal(C.taskNotifications_().naoLidas,0);
console.log('PASS sino de notificações e marcação como vista');
const messageCtx=context('responsavel@example.test');
const msg=C.generalTaskMessageSend_(messageCtx,{id:created.tarefa.id,mensagem:'Documento conferido, falta um dado.'}); commit(messageCtx,msg);
let detail=C.generalTaskDetail_({id:created.tarefa.id});
assert.equal(detail.mensagens.length,1);
assert.match(detail.mensagens[0].mensagem,/falta um dado/);
console.log('PASS diálogo entre responsável e criador');
const pdf=Buffer.from('%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF').toString('base64');
const fileCtx=context('responsavel@example.test');
const attachment=C.generalTaskAttachmentAdd_(fileCtx,{id:created.tarefa.id,nome:'teste.pdf',mime:'application/pdf',base64:pdf}); commit(fileCtx,attachment);
detail=C.generalTaskDetail_({id:created.tarefa.id});
assert.equal(detail.anexos.length,1);
assert.equal(detail.anexos[0].nome,'teste.pdf');
console.log('PASS anexo PDF');
const until=Date.now()+6;while(Date.now()<until){}
as('admin@example.test');
const assignCtx=context('admin@example.test');
const reassigned=C.generalTaskAssign_(assignCtx,{id:created.tarefa.id,responsavel:'segundo@example.test'}); commit(assignCtx,reassigned);
as('segundo@example.test');
notifications=C.taskNotifications_();
assert.equal(notifications.naoLidas,1);
assert.equal(notifications.itens[0].id,created.tarefa.id);
const completeCtx=context('segundo@example.test');
const completed=C.generalTaskComplete_(completeCtx,{id:created.tarefa.id}); commit(completeCtx,completed);
assert.equal(C.get_('Tarefas',created.tarefa.id).situacao,'CONCLUIDA');
console.log('PASS reatribuição, nova notificação e conclusão');
console.log('5 cenários de tarefas aprovados.');

const professor=C.authRegister({nome:'Professor API',email:'prof-api@example.test',funcao:'Professor',senha:'1'});
const aluno=C.authRegister({nome:'Aluno API',email:'aluno-api@example.test',funcao:'Aluno',senha:'1'});
const apiOp=op();
const apiPayload={titulo:'Tarefa pela API',descricao:'Fluxo completo autenticado',responsavel:'aluno-api@example.test',prioridade:'NORMAL',prazo:'2026-11-01',op:apiOp};
const apiCreated=C.api('tarefaGeralCriar',apiPayload,professor.sessionToken);
const apiRepeated=C.api('tarefaGeralCriar',apiPayload,professor.sessionToken);
assert.equal(apiRepeated.tarefa.id,apiCreated.tarefa.id);
let apiNotifications=C.api('notificacoesTarefas',{},aluno.sessionToken);
assert.ok(apiNotifications.itens.some(x=>x.id===apiCreated.tarefa.id));
assert.ok(apiNotifications.naoLidas>=1);
C.api('notificacoesTarefasMarcarLidas',{op:op()},aluno.sessionToken);
apiNotifications=C.api('notificacoesTarefas',{},aluno.sessionToken);
assert.equal(apiNotifications.naoLidas,0);
console.log('PASS API autenticada, lock e idempotência');
console.log('6 cenários de tarefas aprovados.');
