FROM node:22-slim
ENV NODE_ENV=production
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY src ./src
COPY scripts ./scripts
COPY sql ./sql
COPY public ./public
USER node
EXPOSE 8080
CMD ["node","src/server.mjs"]
